name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/NdsApp.LicensingApi/NdsApp.LicensingApi.csproj

      - name: Build
        run: dotnet build src/NdsApp.LicensingApi/NdsApp.LicensingApi.csproj --configuration Release --no-restore
